### ISSUE TITLE
Faulty cron unit tests? 

### ISSUE THREAD

**Issue by jasonjckn** [madstap/recex#6]
Shouldn't your unit test as written... 

``  (is (recex= [{:tue :fri} every-min] (recex/cron->recex "* * * * 2-5")))``

actually be written as

``  (is (recex= [{:tue :wed :thur :fri} every-min] (recex/cron->recex "* * * * 2-5")))``

2-5 is a range, the way you currently have it defined is 2-5 is no different than 2,5

**Comment by jasonjckn** [comment]
If you're still maintaining this repo, I may have time to send you a PR if you agree to look it over.

**Comment by madstap** [comment]
In recex, `{:tue :fri}` is also a range, equivalent to `2-5`. The equivalent to `2,5` would be `#{:tue :fri}` (note that the first one is a map and the second one is a set).

`{:tue :wed :thur :fri}` means two ranges. It's equivalent to `2-3,4-5` (if that's legal cron syntax) and, like the first example, would  include every day from tuesday to friday (inclusive).
